-- DDL profesional para una app de préstamos, cobros por ruta, caja menor
-- y presupuesto operativo.
--
-- Motor objetivo: PostgreSQL 14+
-- Normalización: 4FN. Las dependencias transitivas se resuelven con
-- catálogos y claves foráneas; las dependencias multivaluadas se separan en
-- tablas puente o tablas hijas independientes.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS public;

COMMENT ON SCHEMA public IS
  'Modelo 4FN para préstamos, rutas de cobro, pagos, caja menor y presupuesto.';

SET search_path TO public;

CREATE OR REPLACE FUNCTION actualizar_fecha_modificacion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.actualizado_en = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS moneda (
  codigo_moneda CHAR(3) PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  simbolo VARCHAR(8) NOT NULL,
  decimales SMALLINT NOT NULL DEFAULT 2,
  CONSTRAINT chk_moneda_codigo_mayuscula
    CHECK (codigo_moneda = upper(codigo_moneda)),
  CONSTRAINT chk_moneda_decimales
    CHECK (decimales BETWEEN 0 AND 6)
);

CREATE TABLE IF NOT EXISTS estado_usuario (
  estado_usuario_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS rol (
  rol_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS estado_cliente (
  estado_cliente_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_documento (
  tipo_documento_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_contacto (
  tipo_contacto_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_direccion (
  tipo_direccion_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS estado_ruta (
  estado_ruta_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS frecuencia_pago (
  frecuencia_pago_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL,
  dias_intervalo SMALLINT NOT NULL,
  CONSTRAINT chk_frecuencia_pago_dias
    CHECK (dias_intervalo > 0)
);

CREATE TABLE IF NOT EXISTS estado_credito (
  estado_credito_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS estado_cuota (
  estado_cuota_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS medio_pago (
  medio_pago_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_movimiento_caja (
  tipo_movimiento_caja_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL,
  naturaleza CHAR(1) NOT NULL,
  CONSTRAINT chk_tipo_movimiento_caja_naturaleza
    CHECK (naturaleza IN ('E', 'S'))
);

CREATE TABLE IF NOT EXISTS categoria_gasto (
  categoria_gasto_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS usuario (
  usuario_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  estado_usuario_id SMALLINT NOT NULL
    REFERENCES estado_usuario (estado_usuario_id),
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  correo VARCHAR(180) NOT NULL,
  telefono VARCHAR(40),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_usuario_correo_formato
    CHECK (position('@' in correo) > 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_correo_normalizado
  ON usuario (lower(correo));

CREATE TABLE IF NOT EXISTS usuario_rol (
  usuario_id UUID NOT NULL REFERENCES usuario (usuario_id) ON DELETE CASCADE,
  rol_id SMALLINT NOT NULL REFERENCES rol (rol_id),
  asignado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE IF NOT EXISTS cliente (
  cliente_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  estado_cliente_id SMALLINT NOT NULL
    REFERENCES estado_cliente (estado_cliente_id),
  creado_por_usuario_id UUID REFERENCES usuario (usuario_id),
  nombre_completo VARCHAR(180) NOT NULL,
  nombre_comercial VARCHAR(180),
  notas TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_cliente_nombre_completo
  ON cliente (nombre_completo);

CREATE TABLE IF NOT EXISTS cliente_documento (
  cliente_documento_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL REFERENCES cliente (cliente_id) ON DELETE CASCADE,
  tipo_documento_id SMALLINT NOT NULL
    REFERENCES tipo_documento (tipo_documento_id),
  numero_documento VARCHAR(60) NOT NULL,
  expedido_en VARCHAR(120),
  UNIQUE (tipo_documento_id, numero_documento),
  UNIQUE (cliente_id, tipo_documento_id, numero_documento)
);

CREATE TABLE IF NOT EXISTS cliente_contacto (
  cliente_contacto_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL REFERENCES cliente (cliente_id) ON DELETE CASCADE,
  tipo_contacto_id SMALLINT NOT NULL REFERENCES tipo_contacto (tipo_contacto_id),
  valor VARCHAR(180) NOT NULL,
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  verificado_en TIMESTAMPTZ,
  UNIQUE (cliente_id, tipo_contacto_id, valor)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cliente_contacto_principal
  ON cliente_contacto (cliente_id, tipo_contacto_id)
  WHERE es_principal;

CREATE TABLE IF NOT EXISTS cliente_direccion (
  cliente_direccion_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL REFERENCES cliente (cliente_id) ON DELETE CASCADE,
  tipo_direccion_id SMALLINT NOT NULL
    REFERENCES tipo_direccion (tipo_direccion_id),
  direccion VARCHAR(220) NOT NULL,
  barrio VARCHAR(120),
  municipio VARCHAR(120) NOT NULL,
  departamento VARCHAR(120) NOT NULL,
  pais VARCHAR(80) NOT NULL DEFAULT 'Colombia',
  referencia TEXT,
  latitud NUMERIC(10, 7),
  longitud NUMERIC(10, 7),
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (cliente_id, tipo_direccion_id, direccion)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cliente_direccion_principal
  ON cliente_direccion (cliente_id)
  WHERE es_principal;

CREATE TABLE IF NOT EXISTS ruta (
  ruta_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  responsable_usuario_id UUID NOT NULL REFERENCES usuario (usuario_id),
  estado_ruta_id SMALLINT NOT NULL REFERENCES estado_ruta (estado_ruta_id),
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (responsable_usuario_id, nombre)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ruta_principal_por_responsable
  ON ruta (responsable_usuario_id)
  WHERE es_principal;

CREATE TABLE IF NOT EXISTS ruta_cliente (
  ruta_id UUID NOT NULL REFERENCES ruta (ruta_id) ON DELETE CASCADE,
  cliente_id UUID NOT NULL REFERENCES cliente (cliente_id) ON DELETE RESTRICT,
  orden_visita INTEGER NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  asignado_en DATE NOT NULL DEFAULT CURRENT_DATE,
  PRIMARY KEY (ruta_id, cliente_id),
  UNIQUE (ruta_id, orden_visita),
  CONSTRAINT chk_ruta_cliente_orden
    CHECK (orden_visita > 0)
);

CREATE TABLE IF NOT EXISTS credito (
  credito_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL REFERENCES cliente (cliente_id) ON DELETE RESTRICT,
  ruta_id UUID NOT NULL REFERENCES ruta (ruta_id) ON DELETE RESTRICT,
  moneda_codigo CHAR(3) NOT NULL REFERENCES moneda (codigo_moneda),
  frecuencia_pago_id SMALLINT NOT NULL
    REFERENCES frecuencia_pago (frecuencia_pago_id),
  estado_credito_id SMALLINT NOT NULL REFERENCES estado_credito (estado_credito_id),
  creado_por_usuario_id UUID REFERENCES usuario (usuario_id),
  fecha_inicio DATE NOT NULL,
  valor_principal NUMERIC(14, 2) NOT NULL,
  porcentaje_interes NUMERIC(7, 4) NOT NULL,
  plazo_dias INTEGER NOT NULL,
  omitir_domingos BOOLEAN NOT NULL DEFAULT TRUE,
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_credito_valor_principal
    CHECK (valor_principal > 0),
  CONSTRAINT chk_credito_interes
    CHECK (porcentaje_interes >= 0),
  CONSTRAINT chk_credito_plazo
    CHECK (plazo_dias > 0)
);

CREATE INDEX IF NOT EXISTS ix_credito_cliente
  ON credito (cliente_id);

CREATE INDEX IF NOT EXISTS ix_credito_ruta_estado
  ON credito (ruta_id, estado_credito_id);

CREATE TABLE IF NOT EXISTS credito_plan_pago (
  credito_plan_pago_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  credito_id UUID NOT NULL UNIQUE REFERENCES credito (credito_id) ON DELETE CASCADE,
  numero_cuotas INTEGER NOT NULL,
  valor_cuota NUMERIC(14, 2) NOT NULL,
  valor_total NUMERIC(14, 2) NOT NULL,
  fecha_maxima DATE NOT NULL,
  domingos_omitidos INTEGER NOT NULL DEFAULT 0,
  generado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_plan_pago_cuotas
    CHECK (numero_cuotas > 0),
  CONSTRAINT chk_plan_pago_valores
    CHECK (valor_cuota > 0 AND valor_total > 0),
  CONSTRAINT chk_plan_pago_domingos
    CHECK (domingos_omitidos >= 0)
);

CREATE TABLE IF NOT EXISTS credito_cuota (
  credito_cuota_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  credito_plan_pago_id UUID NOT NULL
    REFERENCES credito_plan_pago (credito_plan_pago_id) ON DELETE CASCADE,
  estado_cuota_id SMALLINT NOT NULL REFERENCES estado_cuota (estado_cuota_id),
  numero_cuota INTEGER NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  valor_capital NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_interes NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_total NUMERIC(14, 2)
    GENERATED ALWAYS AS (valor_capital + valor_interes) STORED,
  UNIQUE (credito_plan_pago_id, numero_cuota),
  CONSTRAINT chk_credito_cuota_numero
    CHECK (numero_cuota > 0),
  CONSTRAINT chk_credito_cuota_valores
    CHECK (valor_capital >= 0 AND valor_interes >= 0)
);

CREATE INDEX IF NOT EXISTS ix_credito_cuota_vencimiento_estado
  ON credito_cuota (fecha_vencimiento, estado_cuota_id);

CREATE TABLE IF NOT EXISTS caja_menor (
  caja_menor_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  responsable_usuario_id UUID NOT NULL REFERENCES usuario (usuario_id),
  moneda_codigo CHAR(3) NOT NULL REFERENCES moneda (codigo_moneda),
  nombre VARCHAR(120) NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  creada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (responsable_usuario_id, nombre)
);

CREATE TABLE IF NOT EXISTS caja_menor_movimiento (
  caja_menor_movimiento_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  caja_menor_id UUID NOT NULL REFERENCES caja_menor (caja_menor_id),
  tipo_movimiento_caja_id SMALLINT NOT NULL
    REFERENCES tipo_movimiento_caja (tipo_movimiento_caja_id),
  usuario_id UUID REFERENCES usuario (usuario_id),
  fecha_movimiento DATE NOT NULL,
  monto NUMERIC(14, 2) NOT NULL,
  motivo TEXT NOT NULL,
  referencia_tabla VARCHAR(80),
  referencia_id UUID,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_caja_menor_movimiento_monto
    CHECK (monto > 0)
);

CREATE INDEX IF NOT EXISTS ix_caja_menor_movimiento_fecha
  ON caja_menor_movimiento (caja_menor_id, fecha_movimiento DESC);

CREATE TABLE IF NOT EXISTS credito_desembolso (
  credito_desembolso_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  credito_id UUID NOT NULL UNIQUE REFERENCES credito (credito_id) ON DELETE RESTRICT,
  caja_menor_movimiento_id UUID UNIQUE
    REFERENCES caja_menor_movimiento (caja_menor_movimiento_id),
  fecha_desembolso DATE NOT NULL,
  monto NUMERIC(14, 2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_credito_desembolso_monto
    CHECK (monto > 0)
);

CREATE TABLE IF NOT EXISTS gasto (
  gasto_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  caja_menor_id UUID REFERENCES caja_menor (caja_menor_id),
  categoria_gasto_id SMALLINT NOT NULL
    REFERENCES categoria_gasto (categoria_gasto_id),
  moneda_codigo CHAR(3) NOT NULL REFERENCES moneda (codigo_moneda),
  registrado_por_usuario_id UUID REFERENCES usuario (usuario_id),
  fecha_gasto DATE NOT NULL,
  monto NUMERIC(14, 2) NOT NULL,
  concepto TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_gasto_monto
    CHECK (monto > 0)
);

CREATE INDEX IF NOT EXISTS ix_gasto_fecha
  ON gasto (fecha_gasto DESC);

CREATE TABLE IF NOT EXISTS pago (
  pago_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL REFERENCES cliente (cliente_id) ON DELETE RESTRICT,
  ruta_id UUID NOT NULL REFERENCES ruta (ruta_id) ON DELETE RESTRICT,
  cobrador_usuario_id UUID REFERENCES usuario (usuario_id),
  medio_pago_id SMALLINT NOT NULL REFERENCES medio_pago (medio_pago_id),
  moneda_codigo CHAR(3) NOT NULL REFERENCES moneda (codigo_moneda),
  fecha_pago TIMESTAMPTZ NOT NULL DEFAULT now(),
  total_pagado NUMERIC(14, 2) NOT NULL,
  referencia_externa VARCHAR(120),
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_pago_total
    CHECK (total_pagado > 0)
);

CREATE INDEX IF NOT EXISTS ix_pago_fecha_ruta
  ON pago (ruta_id, fecha_pago DESC);

CREATE TABLE IF NOT EXISTS pago_aplicacion (
  pago_aplicacion_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pago_id UUID NOT NULL REFERENCES pago (pago_id) ON DELETE CASCADE,
  credito_cuota_id UUID NOT NULL
    REFERENCES credito_cuota (credito_cuota_id) ON DELETE RESTRICT,
  monto_capital NUMERIC(14, 2) NOT NULL DEFAULT 0,
  monto_interes NUMERIC(14, 2) NOT NULL DEFAULT 0,
  monto_mora NUMERIC(14, 2) NOT NULL DEFAULT 0,
  monto_descuento NUMERIC(14, 2) NOT NULL DEFAULT 0,
  UNIQUE (pago_id, credito_cuota_id),
  CONSTRAINT chk_pago_aplicacion_montos
    CHECK (
      monto_capital >= 0
      AND monto_interes >= 0
      AND monto_mora >= 0
      AND monto_descuento >= 0
      AND (monto_capital + monto_interes + monto_mora) > 0
    )
);

CREATE TABLE IF NOT EXISTS presupuesto_periodo (
  presupuesto_periodo_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id UUID REFERENCES usuario (usuario_id),
  moneda_codigo CHAR(3) NOT NULL REFERENCES moneda (codigo_moneda),
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_presupuesto_periodo_fechas
    CHECK (fecha_fin >= fecha_inicio),
  UNIQUE (usuario_id, moneda_codigo, fecha_inicio, fecha_fin)
);

CREATE OR REPLACE VIEW vista_saldo_caja_menor AS
SELECT
  cm.caja_menor_id,
  cm.responsable_usuario_id,
  cm.moneda_codigo,
  COALESCE(
    SUM(
      CASE tmc.naturaleza
        WHEN 'E' THEN cmm.monto
        ELSE -cmm.monto
      END
    ),
    0
  ) AS saldo_caja_menor
FROM caja_menor cm
LEFT JOIN caja_menor_movimiento cmm
  ON cmm.caja_menor_id = cm.caja_menor_id
LEFT JOIN tipo_movimiento_caja tmc
  ON tmc.tipo_movimiento_caja_id = cmm.tipo_movimiento_caja_id
GROUP BY cm.caja_menor_id, cm.responsable_usuario_id, cm.moneda_codigo;

CREATE OR REPLACE VIEW vista_presupuesto_actual AS
SELECT
  cm.caja_menor_id,
  cm.responsable_usuario_id,
  cm.moneda_codigo,
  vscm.saldo_caja_menor AS caja_menor,
  COALESCE(pagos.total_recaudado, 0) AS recaudado,
  COALESCE(gastos.total_gastos, 0) AS gastos,
  COALESCE(desembolsos.total_creditos, 0) AS creditos,
  (
    vscm.saldo_caja_menor
    + COALESCE(pagos.total_recaudado, 0)
    - COALESCE(gastos.total_gastos, 0)
    - COALESCE(desembolsos.total_creditos, 0)
  ) AS presupuesto
FROM caja_menor cm
JOIN vista_saldo_caja_menor vscm
  ON vscm.caja_menor_id = cm.caja_menor_id
LEFT JOIN LATERAL (
  SELECT SUM(p.total_pagado) AS total_recaudado
  FROM pago p
  JOIN ruta r ON r.ruta_id = p.ruta_id
  WHERE r.responsable_usuario_id = cm.responsable_usuario_id
    AND p.moneda_codigo = cm.moneda_codigo
) pagos ON TRUE
LEFT JOIN LATERAL (
  SELECT SUM(g.monto) AS total_gastos
  FROM gasto g
  WHERE g.caja_menor_id = cm.caja_menor_id
    AND g.moneda_codigo = cm.moneda_codigo
) gastos ON TRUE
LEFT JOIN LATERAL (
  SELECT SUM(cd.monto) AS total_creditos
  FROM credito_desembolso cd
  JOIN credito c ON c.credito_id = cd.credito_id
  JOIN ruta r ON r.ruta_id = c.ruta_id
  WHERE r.responsable_usuario_id = cm.responsable_usuario_id
    AND c.moneda_codigo = cm.moneda_codigo
) desembolsos ON TRUE;

DROP TRIGGER IF EXISTS trg_usuario_actualizado ON usuario;
CREATE TRIGGER trg_usuario_actualizado
BEFORE UPDATE ON usuario
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_cliente_actualizado ON cliente;
CREATE TRIGGER trg_cliente_actualizado
BEFORE UPDATE ON cliente
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_ruta_actualizada ON ruta;
CREATE TRIGGER trg_ruta_actualizada
BEFORE UPDATE ON ruta
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_credito_actualizado ON credito;
CREATE TRIGGER trg_credito_actualizado
BEFORE UPDATE ON credito
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_caja_menor_actualizada ON caja_menor;
CREATE TRIGGER trg_caja_menor_actualizada
BEFORE UPDATE ON caja_menor
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_gasto_actualizado ON gasto;
CREATE TRIGGER trg_gasto_actualizado
BEFORE UPDATE ON gasto
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

COMMENT ON TABLE cliente IS
  'Cliente sin contactos ni direcciones embebidas para evitar dependencias multivaluadas.';
COMMENT ON TABLE cliente_contacto IS
  'Contactos del cliente separados por tipo; cumple 4FN para teléfonos, correos y otros medios.';
COMMENT ON TABLE cliente_direccion IS
  'Direcciones del cliente separadas del dato maestro para evitar grupos repetidos.';
COMMENT ON TABLE credito IS
  'Crédito solicitado: valor principal, interés, plazo y frecuencia de pago.';
COMMENT ON TABLE credito_plan_pago IS
  'Resumen contractual del plan generado para el crédito.';
COMMENT ON TABLE credito_cuota IS
  'Cuotas normalizadas del plan de pago; cada cuota es un hecho independiente.';
COMMENT ON TABLE pago_aplicacion IS
  'Distribucion de un pago contra cuotas especificas, separada del encabezado de pago.';
COMMENT ON VIEW vista_presupuesto_actual IS
  'Calcula PRESUPUESTO = CAJA MENOR + RECAUDADO - GASTOS - CRÉDITOS sin guardar totales derivados.';

INSERT INTO moneda (codigo_moneda, nombre, simbolo, decimales) VALUES
  ('COP', 'Peso colombiano', '$', 2),
  ('USD', 'Dólar estadounidense', '$', 2)
ON CONFLICT (codigo_moneda) DO NOTHING;

INSERT INTO estado_usuario (codigo, nombre) VALUES
  ('ACTIVO', 'Activo'),
  ('INACTIVO', 'Inactivo')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO rol (codigo, nombre) VALUES
  ('ADMINISTRADOR', 'Administrador'),
  ('COBRADOR', 'Cobrador'),
  ('AUDITOR', 'Auditor')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_cliente (codigo, nombre) VALUES
  ('ACTIVO', 'Activo'),
  ('SUSPENDIDO', 'Suspendido'),
  ('BLOQUEADO', 'Bloqueado')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_documento (codigo, nombre) VALUES
  ('CC', 'Cédula de ciudadanía'),
  ('CE', 'Cédula de extranjería'),
  ('NIT', 'NIT'),
  ('PASAPORTE', 'Pasaporte')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_contacto (codigo, nombre) VALUES
  ('TELEFONO', 'Teléfono'),
  ('WHATSAPP', 'WhatsApp'),
  ('CORREO', 'Correo electronico')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_direccion (codigo, nombre) VALUES
  ('CASA', 'Casa'),
  ('NEGOCIO', 'Negocio'),
  ('OTRA', 'Otra')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_ruta (codigo, nombre) VALUES
  ('ABIERTA', 'Abierta'),
  ('CERRADA', 'Cerrada'),
  ('PAUSADA', 'Pausada')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO frecuencia_pago (codigo, nombre, dias_intervalo) VALUES
  ('DIARIO', 'Diario', 1),
  ('SEMANAL', 'Semanal', 7),
  ('QUINCENAL', 'Quincenal', 15),
  ('MENSUAL', 'Mensual', 30)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_credito (codigo, nombre) VALUES
  ('CONFIGURADO', 'Configurado'),
  ('ACTIVO', 'Activo'),
  ('PAGADO', 'Pagado'),
  ('VENCIDO', 'Vencido'),
  ('ANULADO', 'Anulado')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_cuota (codigo, nombre) VALUES
  ('PENDIENTE', 'Pendiente'),
  ('PAGADA', 'Pagada'),
  ('VENCIDA', 'Vencida'),
  ('ANULADA', 'Anulada')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO medio_pago (codigo, nombre) VALUES
  ('EFECTIVO', 'Efectivo'),
  ('TRANSFERENCIA', 'Transferencia'),
  ('TARJETA', 'Tarjeta'),
  ('OTRO', 'Otro')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_movimiento_caja (codigo, nombre, naturaleza) VALUES
  ('AJUSTE_ENTRADA', 'Ajuste de entrada', 'E'),
  ('RECAUDO', 'Recaudo', 'E'),
  ('DESEMBOLSO_CREDITO', 'Desembolso de crédito', 'S'),
  ('GASTO', 'Gasto', 'S'),
  ('AJUSTE_SALIDA', 'Ajuste de salida', 'S')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO categoria_gasto (codigo, nombre) VALUES
  ('TRANSPORTE', 'Transporte'),
  ('PAPELERIA', 'Papelería'),
  ('COMISION', 'Comisión'),
  ('OTRO', 'Otro')
ON CONFLICT (codigo) DO NOTHING;

COMMIT;
