-- DDL para la nueva base de datos CobroD a partir del diagrama
-- /home/yisus/Documentos/AppCD/App CobraD.svg.
--
-- Motor objetivo: PostgreSQL 14+.
-- Criterios aplicados:
-- - Los identificadores numericos del diagrama se modelan como BIGINT.
-- - Valores monetarios, totales e intereses se modelan como NUMERIC.
-- - Los campos de estado, tipo, frecuencia e interfaz se modelan como ENUM.
-- - Se agregan UNIQUE en claves naturales y tablas puente para evitar duplicados.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS public;

COMMENT ON SCHEMA public IS
  'Modelo CobroD para usuarios, organizaciones, rutas, creditos, pagos y cajas.';

SET search_path TO public;

DO $$
BEGIN
  CREATE TYPE rol_tipo_enum AS ENUM ('ADMINISTRADOR', 'COBRADOR', 'AUDITOR');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE recurso_interface_enum AS ENUM (
    'WEB',
    'MOBILE',
    'API',
    'BACKOFFICE'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE producto_credito_frecuencia_enum AS ENUM (
    'DIARIO',
    'SEMANAL',
    'QUINCENAL',
    'MENSUAL'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE caja_tipo_enum AS ENUM (
    'PRINCIPAL',
    'MENOR',
    'RECAUDO',
    'OPERATIVA'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE sesion_caja_estado_enum AS ENUM ('ABIERTA', 'CERRADA', 'ANULADA');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE movimiento_caja_tipo_enum AS ENUM (
    'APERTURA',
    'RECAUDO',
    'GASTO',
    'DESEMBOLSO_CREDITO',
    'AJUSTE_ENTRADA',
    'AJUSTE_SALIDA',
    'CIERRE'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE movimiento_referencia_tipo_enum AS ENUM (
    'CREDITO',
    'PAGO',
    'GASTO',
    'SESION_CAJA',
    'AJUSTE'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE credito_estado_enum AS ENUM (
    'CONFIGURADO',
    'ACTIVO',
    'PAGADO',
    'VENCIDO',
    'ANULADO'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE cuota_estado_enum AS ENUM (
    'PENDIENTE',
    'PAGADA',
    'VENCIDA',
    'ANULADA'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE pago_estado_enum AS ENUM ('REGISTRADO', 'CONFIRMADO', 'ANULADO');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE medio_pago_tipo_enum AS ENUM (
    'EFECTIVO',
    'TRANSFERENCIA',
    'TARJETA',
    'BILLETERA',
    'OTRO'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION actualizar_medios_pagos_fecha()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.med_actualizacion = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS tbl_personas (
  id_per BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  per_primer_nombre VARCHAR(120) NOT NULL,
  per_apellido VARCHAR(120) NOT NULL,
  per_documento VARCHAR(60) NOT NULL,
  per_direccion VARCHAR(220),
  per_num_celular VARCHAR(40),
  per_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_personas_documento UNIQUE (per_documento),
  CONSTRAINT chk_tbl_personas_documento
    CHECK (length(trim(per_documento)) > 0)
);

CREATE TABLE IF NOT EXISTS tbl_usuarios (
  id_usu BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usu_usuario VARCHAR(80) NOT NULL,
  usu_password VARCHAR(255) NOT NULL,
  usu_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usu_email VARCHAR(180) NOT NULL,
  usu_activo BOOLEAN NOT NULL DEFAULT TRUE,
  persona_id BIGINT NOT NULL REFERENCES tbl_personas (id_per) ON DELETE RESTRICT,
  CONSTRAINT ux_tbl_usuarios_usuario UNIQUE (usu_usuario),
  CONSTRAINT ux_tbl_usuarios_persona UNIQUE (persona_id),
  CONSTRAINT chk_tbl_usuarios_email
    CHECK (position('@' in usu_email) > 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tbl_usuarios_email_normalizado
  ON tbl_usuarios (lower(usu_email));

CREATE TABLE IF NOT EXISTS tbl_roles (
  id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_tip rol_tipo_enum NOT NULL,
  rol_nivel BIGINT NOT NULL,
  rol_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_roles_tipo UNIQUE (rol_tip),
  CONSTRAINT chk_tbl_roles_nivel CHECK (rol_nivel > 0)
);

CREATE TABLE IF NOT EXISTS tbl_recursos (
  id_rec BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(120) NOT NULL,
  rec_icono VARCHAR(80),
  rec_orden BIGINT NOT NULL DEFAULT 0,
  rec_interface recurso_interface_enum NOT NULL DEFAULT 'WEB',
  CONSTRAINT ux_tbl_recursos_interface_nombre UNIQUE (rec_interface, nom),
  CONSTRAINT chk_tbl_recursos_orden CHECK (rec_orden >= 0)
);

CREATE TABLE IF NOT EXISTS tbl_roles_recursos (
  id_ror BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rec_id BIGINT NOT NULL REFERENCES tbl_recursos (id_rec) ON DELETE CASCADE,
  rol_id BIGINT NOT NULL REFERENCES tbl_roles (id_rol) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_roles_recursos UNIQUE (rec_id, rol_id)
);

CREATE TABLE IF NOT EXISTS tbl_organizaciones (
  id_org BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_nombre VARCHAR(160) NOT NULL,
  org_telefono VARCHAR(40),
  org_email VARCHAR(180),
  org_activo BOOLEAN NOT NULL DEFAULT TRUE,
  org_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_organizaciones_nombre UNIQUE (org_nombre),
  CONSTRAINT chk_tbl_organizaciones_email
    CHECK (org_email IS NULL OR position('@' in org_email) > 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tbl_organizaciones_email_normalizado
  ON tbl_organizaciones (lower(org_email))
  WHERE org_email IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_usuarios_organizaciones (
  id_urg BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  urg_activo BOOLEAN NOT NULL DEFAULT TRUE,
  rol_id BIGINT NOT NULL REFERENCES tbl_roles (id_rol) ON DELETE RESTRICT,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_usuarios_organizaciones UNIQUE (usu_id, org_id, rol_id)
);

CREATE TABLE IF NOT EXISTS tbl_clientes (
  id_cli BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_referencia VARCHAR(120),
  cli_activo BOOLEAN NOT NULL DEFAULT TRUE,
  cli_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  cli_persona BIGINT NOT NULL REFERENCES tbl_personas (id_per) ON DELETE RESTRICT,
  CONSTRAINT ux_tbl_clientes_org_persona UNIQUE (org_id, cli_persona),
  CONSTRAINT ux_tbl_clientes_org_referencia UNIQUE (org_id, cli_referencia)
);

CREATE TABLE IF NOT EXISTS tbl_rutas (
  id_rut BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut_nombre VARCHAR(120) NOT NULL,
  rut_descripcion VARCHAR(500),
  rut_activa BOOLEAN NOT NULL DEFAULT TRUE,
  rut_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_rutas_org_nombre UNIQUE (org_id, rut_nombre)
);

CREATE INDEX IF NOT EXISTS ix_tbl_rutas_usuario
  ON tbl_rutas (usu_id);

CREATE TABLE IF NOT EXISTS tbl_rutas_clientes (
  id_rcl BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rcl_activo BOOLEAN NOT NULL DEFAULT TRUE,
  rcl_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  rut_id BIGINT NOT NULL REFERENCES tbl_rutas (id_rut) ON DELETE CASCADE,
  cli_id BIGINT NOT NULL REFERENCES tbl_clientes (id_cli) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_rutas_clientes UNIQUE (rut_id, cli_id)
);

CREATE TABLE IF NOT EXISTS tbl_productos_creditos (
  id_pcr BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pcr_nombre VARCHAR(120) NOT NULL,
  pcr_frecuencia producto_credito_frecuencia_enum NOT NULL,
  pcr_tasa_interes NUMERIC(7, 4) NOT NULL,
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_productos_creditos_org_nombre UNIQUE (org_id, pcr_nombre),
  CONSTRAINT chk_tbl_productos_creditos_tasa
    CHECK (pcr_tasa_interes >= 0)
);

CREATE TABLE IF NOT EXISTS tbl_categorias_gastos (
  id_cga BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cga_nombre VARCHAR(120) NOT NULL,
  cga_descripcion VARCHAR(500),
  CONSTRAINT ux_tbl_categorias_gastos_nombre UNIQUE (cga_nombre)
);

CREATE TABLE IF NOT EXISTS tbl_cajas (
  id_caj BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caj_nombre VARCHAR(120) NOT NULL,
  caj_tipo caja_tipo_enum NOT NULL DEFAULT 'MENOR',
  caj_activa BOOLEAN NOT NULL DEFAULT TRUE,
  caj_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_cajas_org_nombre UNIQUE (org_id, caj_nombre)
);

CREATE TABLE IF NOT EXISTS tbl_gastos (
  id_gas BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gas_fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
  gas_monto NUMERIC(14, 2) NOT NULL,
  caj_id BIGINT NOT NULL REFERENCES tbl_cajas (id_caj) ON DELETE RESTRICT,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  cga_id BIGINT NOT NULL REFERENCES tbl_categorias_gastos (id_cga) ON DELETE RESTRICT,
  CONSTRAINT chk_tbl_gastos_monto CHECK (gas_monto > 0)
);

ALTER TABLE tbl_cajas
  ADD COLUMN IF NOT EXISTS gas_id BIGINT;

DO $$
BEGIN
  ALTER TABLE tbl_cajas
    ADD CONSTRAINT fk_tbl_cajas_gasto
    FOREIGN KEY (gas_id) REFERENCES tbl_gastos (id_gas) ON DELETE SET NULL;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS tbl_sesiones_cajas (
  id_sca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sca_fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT now(),
  sca_fecha_cierre TIMESTAMPTZ,
  sca_monto_inicial NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sca_total_cobrado NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sca_total_gasto NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sca_estado sesion_caja_estado_enum NOT NULL DEFAULT 'ABIERTA',
  caj_id BIGINT NOT NULL REFERENCES tbl_cajas (id_caj) ON DELETE RESTRICT,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  CONSTRAINT chk_tbl_sesiones_cajas_montos
    CHECK (
      sca_monto_inicial >= 0
      AND sca_total_cobrado >= 0
      AND sca_total_gasto >= 0
    ),
  CONSTRAINT chk_tbl_sesiones_cajas_fechas
    CHECK (sca_fecha_cierre IS NULL OR sca_fecha_cierre >= sca_fecha_apertura)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tbl_sesiones_cajas_abierta
  ON tbl_sesiones_cajas (caj_id)
  WHERE sca_estado = 'ABIERTA';

CREATE TABLE IF NOT EXISTS tbl_movimientos_cajas (
  id_mca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mca_tipo movimiento_caja_tipo_enum NOT NULL,
  mca_monto NUMERIC(14, 2) NOT NULL,
  mca_referencia_id BIGINT,
  mca_referencia_tipo movimiento_referencia_tipo_enum,
  mca_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  sca_id BIGINT REFERENCES tbl_sesiones_cajas (id_sca) ON DELETE SET NULL,
  CONSTRAINT chk_tbl_movimientos_cajas_monto CHECK (mca_monto > 0),
  CONSTRAINT chk_tbl_movimientos_cajas_referencia
    CHECK (
      (mca_referencia_id IS NULL AND mca_referencia_tipo IS NULL)
      OR (mca_referencia_id IS NOT NULL AND mca_referencia_tipo IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_tbl_movimientos_cajas_org_fecha
  ON tbl_movimientos_cajas (org_id, mca_creacion DESC);

CREATE TABLE IF NOT EXISTS tbl_creditos (
  id_cre BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cre_total NUMERIC(14, 2) NOT NULL,
  cre_estado credito_estado_enum NOT NULL DEFAULT 'ACTIVO',
  cre_tasa_interes NUMERIC(7, 4) NOT NULL,
  cre_interes_total NUMERIC(14, 2) NOT NULL,
  cre_total_pagar NUMERIC(14, 2) NOT NULL,
  cre_fecha_inicio DATE NOT NULL,
  cre_fecha_fin DATE NOT NULL,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  pcr_id BIGINT NOT NULL REFERENCES tbl_productos_creditos (id_pcr) ON DELETE RESTRICT,
  cli_id BIGINT NOT NULL REFERENCES tbl_clientes (id_cli) ON DELETE RESTRICT,
  CONSTRAINT chk_tbl_creditos_valores
    CHECK (
      cre_total > 0
      AND cre_tasa_interes >= 0
      AND cre_interes_total >= 0
      AND cre_total_pagar >= cre_total
    ),
  CONSTRAINT chk_tbl_creditos_fechas
    CHECK (cre_fecha_fin >= cre_fecha_inicio)
);

CREATE INDEX IF NOT EXISTS ix_tbl_creditos_cliente_estado
  ON tbl_creditos (cli_id, cre_estado);

CREATE INDEX IF NOT EXISTS ix_tbl_creditos_usuario_estado
  ON tbl_creditos (usu_id, cre_estado);

CREATE TABLE IF NOT EXISTS tbl_cuotas (
  id_cuo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuo_numero BIGINT NOT NULL,
  cuo_valor NUMERIC(14, 2) NOT NULL,
  cuo_total_pagado NUMERIC(14, 2) NOT NULL DEFAULT 0,
  cuo_estado cuota_estado_enum NOT NULL DEFAULT 'PENDIENTE',
  cuo_fecha_vencimiento DATE NOT NULL,
  cre_id BIGINT NOT NULL REFERENCES tbl_creditos (id_cre) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_cuotas_credito_numero UNIQUE (cre_id, cuo_numero),
  CONSTRAINT chk_tbl_cuotas_valores
    CHECK (
      cuo_numero > 0
      AND cuo_valor > 0
      AND cuo_total_pagado >= 0
      AND cuo_total_pagado <= cuo_valor
    )
);

CREATE INDEX IF NOT EXISTS ix_tbl_cuotas_vencimiento_estado
  ON tbl_cuotas (cuo_fecha_vencimiento, cuo_estado);

CREATE TABLE IF NOT EXISTS tbl_medios_pagos (
  id_med BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  med_nombre VARCHAR(120) NOT NULL,
  med_tipo medio_pago_tipo_enum NOT NULL,
  med_proveedor VARCHAR(120),
  med_referencia_cuenta VARCHAR(120),
  med_titular VARCHAR(180),
  med_activo BOOLEAN NOT NULL DEFAULT TRUE,
  med_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  med_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_medios_pagos_org_nombre UNIQUE (org_id, med_nombre),
  CONSTRAINT ux_tbl_medios_pagos_org_referencia
    UNIQUE (org_id, med_referencia_cuenta)
);

CREATE TABLE IF NOT EXISTS tbl_pagos (
  id_pag BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pag_monto NUMERIC(14, 2) NOT NULL,
  pag_fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
  pag_referencia VARCHAR(120),
  pag_idempotency_llave UUID NOT NULL DEFAULT gen_random_uuid(),
  pag_estado pago_estado_enum NOT NULL DEFAULT 'REGISTRADO',
  med_id BIGINT NOT NULL REFERENCES tbl_medios_pagos (id_med) ON DELETE RESTRICT,
  cre_id BIGINT NOT NULL REFERENCES tbl_creditos (id_cre) ON DELETE RESTRICT,
  CONSTRAINT ux_tbl_pagos_idempotency UNIQUE (pag_idempotency_llave),
  CONSTRAINT chk_tbl_pagos_monto CHECK (pag_monto > 0)
);

CREATE INDEX IF NOT EXISTS ix_tbl_pagos_credito_fecha
  ON tbl_pagos (cre_id, pag_fecha DESC);

CREATE TABLE IF NOT EXISTS tbl_cuotas_pagos (
  id_cpa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpa_numero BIGINT,
  cpa_capital NUMERIC(14, 2) NOT NULL DEFAULT 0,
  cpa_interes NUMERIC(14, 2) NOT NULL DEFAULT 0,
  cpa_total NUMERIC(14, 2)
    GENERATED ALWAYS AS (cpa_capital + cpa_interes) STORED,
  cuo_id BIGINT NOT NULL REFERENCES tbl_cuotas (id_cuo) ON DELETE RESTRICT,
  pagos_id BIGINT NOT NULL REFERENCES tbl_pagos (id_pag) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_cuotas_pagos UNIQUE (cuo_id, pagos_id),
  CONSTRAINT chk_tbl_cuotas_pagos_montos
    CHECK (cpa_capital >= 0 AND cpa_interes >= 0 AND cpa_total > 0)
);

CREATE OR REPLACE VIEW vista_creditos_saldos AS
SELECT
  cr.id_cre,
  cr.cli_id,
  cr.usu_id,
  cr.cre_estado,
  cr.cre_total,
  cr.cre_interes_total,
  cr.cre_total_pagar,
  COALESCE(SUM(cp.cpa_total), 0) AS total_pagado,
  GREATEST(cr.cre_total_pagar - COALESCE(SUM(cp.cpa_total), 0), 0) AS saldo
FROM tbl_creditos cr
LEFT JOIN tbl_cuotas cu
  ON cu.cre_id = cr.id_cre
LEFT JOIN tbl_cuotas_pagos cp
  ON cp.cuo_id = cu.id_cuo
GROUP BY cr.id_cre;

<<<<<<< Updated upstream
CREATE OR REPLACE VIEW vista_presupuesto_actual AS
WITH caja_recaudo AS (
  SELECT DISTINCT ON (cm.responsable_usuario_id, cm.moneda_codigo)
    cm.caja_menor_id,
    cm.responsable_usuario_id,
    cm.moneda_codigo
  FROM caja_menor cm
  WHERE cm.activa = TRUE
  ORDER BY
    cm.responsable_usuario_id,
    cm.moneda_codigo,
    cm.creada_en ASC,
    cm.caja_menor_id ASC
)
SELECT
  cm.caja_menor_id,
  cm.responsable_usuario_id,
  cm.moneda_codigo,
  vscm.saldo_caja_menor AS caja_menor,
  CASE
    WHEN cr.caja_menor_id = cm.caja_menor_id THEN COALESCE(pagos.total_recaudado, 0)
    ELSE 0
  END AS recaudado,
  COALESCE(gastos.total_gastos, 0) AS gastos,
  COALESCE(desembolsos.total_creditos, 0) AS creditos,
  (
    vscm.saldo_caja_menor
    + CASE
        WHEN cr.caja_menor_id = cm.caja_menor_id THEN COALESCE(pagos.total_recaudado, 0)
        ELSE 0
      END
    - COALESCE(gastos.total_gastos, 0)
  ) AS presupuesto
FROM caja_menor cm
JOIN vista_saldo_caja_menor vscm
  ON vscm.caja_menor_id = cm.caja_menor_id
LEFT JOIN caja_recaudo cr
  ON cr.responsable_usuario_id = cm.responsable_usuario_id
 AND cr.moneda_codigo = cm.moneda_codigo
LEFT JOIN LATERAL (
  SELECT SUM(p.total_pagado) AS total_recaudado
  FROM pago p
  JOIN ruta r ON r.ruta_id = p.ruta_id
  WHERE r.responsable_usuario_id = cm.responsable_usuario_id
    AND p.moneda_codigo = cm.moneda_codigo
) pagos ON TRUE
LEFT JOIN LATERAL (
  SELECT SUM(g.monto) AS total_gastos
  FROM gasto g
  WHERE g.caja_menor_id = cm.caja_menor_id
    AND g.moneda_codigo = cm.moneda_codigo
) gastos ON TRUE
LEFT JOIN LATERAL (
  SELECT SUM(cd.monto) AS total_creditos
  FROM credito_desembolso cd
  JOIN caja_menor_movimiento cmm
    ON cmm.caja_menor_movimiento_id = cd.caja_menor_movimiento_id
  JOIN credito c ON c.credito_id = cd.credito_id
  JOIN ruta r ON r.ruta_id = c.ruta_id
  WHERE r.responsable_usuario_id = cm.responsable_usuario_id
    AND c.moneda_codigo = cm.moneda_codigo
    AND cmm.caja_menor_id = cm.caja_menor_id
) desembolsos ON TRUE;
=======
DROP TRIGGER IF EXISTS trg_tbl_medios_pagos_actualizacion ON tbl_medios_pagos;
CREATE TRIGGER trg_tbl_medios_pagos_actualizacion
BEFORE UPDATE ON tbl_medios_pagos
FOR EACH ROW EXECUTE FUNCTION actualizar_medios_pagos_fecha();
>>>>>>> Stashed changes

COMMENT ON TABLE tbl_personas IS
  'Datos base de personas reutilizados por usuarios y clientes.';
COMMENT ON TABLE tbl_usuarios_organizaciones IS
  'Tabla puente entre usuarios, organizaciones y roles.';
COMMENT ON TABLE tbl_rutas_clientes IS
  'Tabla puente que asigna clientes a rutas.';
COMMENT ON TABLE tbl_productos_creditos IS
  'Productos de credito por organizacion, frecuencia e interes.';
COMMENT ON TABLE tbl_cuotas_pagos IS
  'Aplicacion de pagos contra cuotas especificas.';
COMMENT ON VIEW vista_creditos_saldos IS
  'Saldo de cada credito calculado desde cuotas y aplicaciones de pago.';

INSERT INTO tbl_roles (rol_tip, rol_nivel) VALUES
  ('ADMINISTRADOR', 1),
  ('COBRADOR', 2),
  ('AUDITOR', 3)
ON CONFLICT (rol_tip) DO NOTHING;

<<<<<<< Updated upstream
DROP TRIGGER IF EXISTS trg_ruta_actualizada ON ruta;
CREATE TRIGGER trg_ruta_actualizada
BEFORE UPDATE ON ruta
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_credito_actualizado ON credito;
CREATE TRIGGER trg_credito_actualizado
BEFORE UPDATE ON credito
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_caja_menor_actualizada ON caja_menor;
CREATE TRIGGER trg_caja_menor_actualizada
BEFORE UPDATE ON caja_menor
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_gasto_actualizado ON gasto;
CREATE TRIGGER trg_gasto_actualizado
BEFORE UPDATE ON gasto
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();

COMMENT ON TABLE cliente IS
  'Cliente sin contactos ni direcciones embebidas para evitar dependencias multivaluadas.';
COMMENT ON TABLE cliente_contacto IS
  'Contactos del cliente separados por tipo; cumple 4FN para teléfonos, correos y otros medios.';
COMMENT ON TABLE cliente_direccion IS
  'Direcciones del cliente separadas del dato maestro para evitar grupos repetidos.';
COMMENT ON TABLE credito IS
  'Crédito solicitado: valor principal, interés, plazo y frecuencia de pago.';
COMMENT ON TABLE credito_plan_pago IS
  'Resumen contractual del plan generado para el crédito.';
COMMENT ON TABLE credito_cuota IS
  'Cuotas normalizadas del plan de pago; cada cuota es un hecho independiente.';
COMMENT ON TABLE pago_aplicacion IS
  'Distribucion de un pago contra cuotas especificas, separada del encabezado de pago.';
COMMENT ON VIEW vista_presupuesto_actual IS
  'Calcula PRESUPUESTO = CAJA MENOR + RECAUDADO - GASTOS sin duplicar recaudos por caja ni volver a restar creditos ya reflejados en caja menor.';

INSERT INTO moneda (codigo_moneda, nombre, simbolo, decimales) VALUES
  ('COP', 'Peso colombiano', '$', 2),
  ('USD', 'Dólar estadounidense', '$', 2)
ON CONFLICT (codigo_moneda) DO NOTHING;

INSERT INTO estado_usuario (codigo, nombre) VALUES
  ('ACTIVO', 'Activo'),
  ('INACTIVO', 'Inactivo')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO rol (codigo, nombre) VALUES
  ('ADMINISTRADOR', 'Administrador'),
  ('COBRADOR', 'Cobrador'),
  ('AUDITOR', 'Auditor')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_cliente (codigo, nombre) VALUES
  ('ACTIVO', 'Activo'),
  ('SUSPENDIDO', 'Suspendido'),
  ('BLOQUEADO', 'Bloqueado')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_documento (codigo, nombre) VALUES
  ('CC', 'Cédula de ciudadanía'),
  ('CE', 'Cédula de extranjería'),
  ('NIT', 'NIT'),
  ('PASAPORTE', 'Pasaporte')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_contacto (codigo, nombre) VALUES
  ('TELEFONO', 'Teléfono'),
  ('WHATSAPP', 'WhatsApp'),
  ('CORREO', 'Correo electronico')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_direccion (codigo, nombre) VALUES
  ('CASA', 'Casa'),
  ('NEGOCIO', 'Negocio'),
  ('OTRA', 'Otra')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_ruta (codigo, nombre) VALUES
  ('ABIERTA', 'Abierta'),
  ('CERRADA', 'Cerrada'),
  ('PAUSADA', 'Pausada')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO frecuencia_pago (codigo, nombre, dias_intervalo) VALUES
  ('DIARIO', 'Diario', 1),
  ('SEMANAL', 'Semanal', 7),
  ('QUINCENAL', 'Quincenal', 15),
  ('MENSUAL', 'Mensual', 30)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_credito (codigo, nombre) VALUES
  ('CONFIGURADO', 'Configurado'),
  ('ACTIVO', 'Activo'),
  ('PAGADO', 'Pagado'),
  ('VENCIDO', 'Vencido'),
  ('ANULADO', 'Anulado')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO estado_cuota (codigo, nombre) VALUES
  ('PENDIENTE', 'Pendiente'),
  ('PAGADA', 'Pagada'),
  ('VENCIDA', 'Vencida'),
  ('ANULADA', 'Anulada')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO medio_pago (codigo, nombre) VALUES
  ('EFECTIVO', 'Efectivo'),
  ('TRANSFERENCIA', 'Transferencia'),
  ('TARJETA', 'Tarjeta'),
  ('OTRO', 'Otro')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipo_movimiento_caja (codigo, nombre, naturaleza) VALUES
  ('AJUSTE_ENTRADA', 'Ajuste de entrada', 'E'),
  ('RECAUDO', 'Recaudo', 'E'),
  ('DESEMBOLSO_CREDITO', 'Desembolso de crédito', 'S'),
  ('GASTO', 'Gasto', 'S'),
  ('AJUSTE_SALIDA', 'Ajuste de salida', 'S')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO categoria_gasto (codigo, nombre) VALUES
  ('TRANSPORTE', 'Transporte'),
  ('PAPELERIA', 'Papelería'),
  ('COMISION', 'Comisión'),
  ('OTRO', 'Otro')
ON CONFLICT (codigo) DO NOTHING;
=======
INSERT INTO tbl_categorias_gastos (cga_nombre, cga_descripcion) VALUES
  ('TRANSPORTE', 'Gastos de transporte'),
  ('PAPELERIA', 'Papeleria e insumos'),
  ('COMISION', 'Comisiones operativas'),
  ('OTRO', 'Otros gastos')
ON CONFLICT (cga_nombre) DO NOTHING;
>>>>>>> Stashed changes

COMMIT;
