-- Script pasteable para Supabase SQL Editor.
--
-- Uso:
-- 1. Abrir Supabase Dashboard > SQL Editor.
-- 2. Pegar este archivo completo.
-- 3. Ejecutar.
--
-- Este script NO elimina tablas anteriores del modelo de prueba. Crea/actualiza
-- el nuevo modelo CobroD con tablas tbl_* y tipos ENUM. Si necesitas limpiar el
-- modelo viejo, hazlo en un script separado y con backup previo.
--
-- DDL para la nueva base de datos CobroD a partir del diagrama
--
-- Motor objetivo: PostgreSQL 14+.
-- Criterios aplicados:
-- - Los identificadores numericos del diagrama se modelan como BIGINT.
-- - Valores monetarios, totales e intereses se modelan como NUMERIC.
-- - Los campos de estado, tipo, frecuencia e interfaz se modelan como ENUM.
-- - Se agregan UNIQUE en claves naturales y tablas puente para evitar duplicados.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS public;

COMMENT ON SCHEMA public IS
  'Modelo CobroD para usuarios, organizaciones, rutas, creditos, pagos y cajas.';

SET search_path TO public;

-- Tabla tecnica de Prisma Migrate.
-- Prisma la usa para saber que migraciones ya fueron aplicadas en esta base.
-- No representa una entidad del negocio CobroD, pero conviene conservarla si
-- el proyecto seguira usando comandos como prisma migrate dev/deploy.
CREATE TABLE IF NOT EXISTS public._prisma_migrations (
  id VARCHAR(36) PRIMARY KEY,
  checksum VARCHAR(64) NOT NULL,
  finished_at TIMESTAMPTZ,
  migration_name VARCHAR(255) NOT NULL,
  logs TEXT,
  rolled_back_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);

DO $$
BEGIN
  CREATE TYPE rol_tipo_enum AS ENUM (
    'SUPER_ADMIN',
    'ADMINISTRADOR',
    'COBRADOR',
    'AUDITOR'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE recurso_interface_enum AS ENUM (
    'WEB',
    'MOBILE',
    'API',
    'BACKOFFICE'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE producto_credito_frecuencia_enum AS ENUM (
    'DIARIO',
    'SEMANAL',
    'QUINCENAL',
    'MENSUAL'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE caja_tipo_enum AS ENUM (
    'PRINCIPAL',
    'MENOR',
    'RECAUDO',
    'OPERATIVA'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE sesion_caja_estado_enum AS ENUM ('ABIERTA', 'CERRADA', 'ANULADA');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE movimiento_caja_tipo_enum AS ENUM (
    'APERTURA',
    'RECAUDO',
    'GASTO',
    'DESEMBOLSO_CREDITO',
    'AJUSTE_ENTRADA',
    'AJUSTE_SALIDA',
    'CIERRE'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE movimiento_referencia_tipo_enum AS ENUM (
    'CREDITO',
    'PAGO',
    'GASTO',
    'SESION_CAJA',
    'AJUSTE'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE credito_estado_enum AS ENUM (
    'CONFIGURADO',
    'ACTIVO',
    'PAGADO',
    'VENCIDO',
    'ANULADO'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE cuota_estado_enum AS ENUM (
    'PENDIENTE',
    'PAGADA',
    'VENCIDA',
    'ANULADA'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE pago_estado_enum AS ENUM ('REGISTRADO', 'CONFIRMADO', 'ANULADO');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE medio_pago_tipo_enum AS ENUM (
    'EFECTIVO',
    'TRANSFERENCIA',
    'TARJETA',
    'BILLETERA',
    'OTRO'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE wompi_tipo_pago_enum AS ENUM (
    'ORGANIZACION_PLAN',
    'ORGANIZACION_RENOVACION',
    'CLIENTE_CREDITO'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE wompi_estado_enum AS ENUM (
    'PENDIENTE',
    'APROBADA',
    'RECHAZADA',
    'EXPIRADA',
    'ANULADA'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION actualizar_medios_pagos_fecha()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.med_actualizacion = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS tbl_personas (
  id_per BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  per_primer_nombre VARCHAR(120) NOT NULL,
  per_apellido VARCHAR(120) NOT NULL,
  per_documento VARCHAR(60) NOT NULL,
  per_direccion VARCHAR(220),
  per_num_celular VARCHAR(40),
  per_email VARCHAR(180),
  per_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_personas_documento UNIQUE (per_documento),
  CONSTRAINT chk_tbl_personas_documento
    CHECK (length(trim(per_documento)) > 0),
  CONSTRAINT chk_tbl_personas_email
    CHECK (per_email IS NULL OR position('@' in per_email) > 1)
);

ALTER TABLE tbl_personas
  ADD COLUMN IF NOT EXISTS per_email VARCHAR(180);

DO $$
BEGIN
  ALTER TABLE tbl_personas
    ADD CONSTRAINT chk_tbl_personas_email
    CHECK (per_email IS NULL OR position('@' in per_email) > 1);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS tbl_usuarios (
  id_usu BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usu_usuario VARCHAR(80) NOT NULL,
  usu_password VARCHAR(255) NOT NULL,
  usu_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usu_activo BOOLEAN NOT NULL DEFAULT TRUE,
  persona_id BIGINT NOT NULL REFERENCES tbl_personas (id_per) ON DELETE RESTRICT,
  CONSTRAINT ux_tbl_usuarios_usuario UNIQUE (usu_usuario),
  CONSTRAINT ux_tbl_usuarios_persona UNIQUE (persona_id)
);

CREATE INDEX IF NOT EXISTS ix_tbl_personas_email_normalizado
  ON tbl_personas (lower(per_email))
  WHERE per_email IS NOT NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'tbl_usuarios'
      AND column_name = 'usu_email'
  ) THEN
    EXECUTE $migrar_usu_email$
      UPDATE tbl_personas persona
      SET per_email = lower(usuario.usu_email)
      FROM tbl_usuarios usuario
      WHERE usuario.persona_id = persona.id_per
        AND persona.per_email IS NULL
        AND usuario.usu_email IS NOT NULL
    $migrar_usu_email$;
  END IF;
END;
$$;

DROP INDEX IF EXISTS ux_tbl_usuarios_email_normalizado;

ALTER TABLE tbl_usuarios
  DROP CONSTRAINT IF EXISTS chk_tbl_usuarios_email,
  DROP COLUMN IF EXISTS usu_email;

CREATE TABLE IF NOT EXISTS tbl_roles (
  id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_tip rol_tipo_enum NOT NULL,
  rol_nivel BIGINT NOT NULL,
  rol_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_roles_tipo UNIQUE (rol_tip),
  CONSTRAINT chk_tbl_roles_nivel CHECK (rol_nivel > 0)
);

CREATE TABLE IF NOT EXISTS tbl_recursos (
  id_rec BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(120) NOT NULL,
  rec_icono VARCHAR(80),
  rec_orden BIGINT NOT NULL DEFAULT 0,
  rec_interface recurso_interface_enum NOT NULL DEFAULT 'WEB',
  CONSTRAINT ux_tbl_recursos_interface_nombre UNIQUE (rec_interface, nom),
  CONSTRAINT chk_tbl_recursos_orden CHECK (rec_orden >= 0)
);

CREATE TABLE IF NOT EXISTS tbl_roles_recursos (
  id_ror BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rec_id BIGINT NOT NULL REFERENCES tbl_recursos (id_rec) ON DELETE CASCADE,
  rol_id BIGINT NOT NULL REFERENCES tbl_roles (id_rol) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_roles_recursos UNIQUE (rec_id, rol_id)
);

CREATE TABLE IF NOT EXISTS tbl_organizaciones (
  id_org BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_nombre VARCHAR(160) NOT NULL,
  org_telefono VARCHAR(40),
  org_email VARCHAR(180),
  org_activo BOOLEAN NOT NULL DEFAULT TRUE,
  org_monto_plan NUMERIC NOT NULL DEFAULT 0,
  org_moneda_plan CHAR(3) NOT NULL DEFAULT 'COP',
  org_acceso_hasta DATE,
  org_suspendida_en TIMESTAMPTZ,
  org_motivo_suspension VARCHAR(220),
  org_es_sistema BOOLEAN NOT NULL DEFAULT FALSE,
  org_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_organizaciones_nombre UNIQUE (org_nombre),
  CONSTRAINT chk_tbl_organizaciones_email
    CHECK (org_email IS NULL OR position('@' in org_email) > 1),
  CONSTRAINT chk_tbl_organizaciones_monto_plan CHECK (org_monto_plan >= 0),
  CONSTRAINT chk_tbl_organizaciones_moneda_plan
    CHECK (org_moneda_plan = upper(org_moneda_plan))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tbl_organizaciones_email_normalizado
  ON tbl_organizaciones (lower(org_email))
  WHERE org_email IS NOT NULL;

ALTER TABLE tbl_organizaciones
  ADD COLUMN IF NOT EXISTS org_monto_plan NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS org_moneda_plan CHAR(3) NOT NULL DEFAULT 'COP',
  ADD COLUMN IF NOT EXISTS org_acceso_hasta DATE,
  ADD COLUMN IF NOT EXISTS org_suspendida_en TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS org_motivo_suspension VARCHAR(220),
  ADD COLUMN IF NOT EXISTS org_es_sistema BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
  ALTER TABLE tbl_organizaciones
    ADD CONSTRAINT chk_tbl_organizaciones_monto_plan
    CHECK (org_monto_plan >= 0);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  ALTER TABLE tbl_organizaciones
    ADD CONSTRAINT chk_tbl_organizaciones_moneda_plan
    CHECK (org_moneda_plan = upper(org_moneda_plan));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE INDEX IF NOT EXISTS ix_tbl_organizaciones_acceso
  ON tbl_organizaciones (org_activo, org_acceso_hasta)
  WHERE NOT org_es_sistema;

CREATE TABLE IF NOT EXISTS tbl_usuarios_organizaciones (
  id_urg BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  urg_activo BOOLEAN NOT NULL DEFAULT TRUE,
  rol_id BIGINT NOT NULL REFERENCES tbl_roles (id_rol) ON DELETE RESTRICT,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_usuarios_organizaciones UNIQUE (usu_id, org_id, rol_id)
);

CREATE TABLE IF NOT EXISTS tbl_clientes (
  id_cli BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_referencia VARCHAR(120),
  cli_activo BOOLEAN NOT NULL DEFAULT TRUE,
  cli_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  cli_persona BIGINT NOT NULL REFERENCES tbl_personas (id_per) ON DELETE RESTRICT,
  CONSTRAINT ux_tbl_clientes_org_persona UNIQUE (org_id, cli_persona),
  CONSTRAINT ux_tbl_clientes_org_referencia UNIQUE (org_id, cli_referencia)
);

CREATE TABLE IF NOT EXISTS tbl_rutas (
  id_rut BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut_nombre VARCHAR(120) NOT NULL,
  rut_descripcion VARCHAR(500),
  rut_activa BOOLEAN NOT NULL DEFAULT TRUE,
  rut_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_rutas_org_nombre UNIQUE (org_id, rut_nombre)
);

CREATE INDEX IF NOT EXISTS ix_tbl_rutas_usuario
  ON tbl_rutas (usu_id);

CREATE TABLE IF NOT EXISTS tbl_rutas_clientes (
  id_rcl BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rcl_activo BOOLEAN NOT NULL DEFAULT TRUE,
  rcl_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  rut_id BIGINT NOT NULL REFERENCES tbl_rutas (id_rut) ON DELETE CASCADE,
  cli_id BIGINT NOT NULL REFERENCES tbl_clientes (id_cli) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_rutas_clientes UNIQUE (rut_id, cli_id)
);

CREATE TABLE IF NOT EXISTS tbl_productos_creditos (
  id_pcr BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pcr_nombre VARCHAR(120) NOT NULL,
  pcr_frecuencia producto_credito_frecuencia_enum NOT NULL,
  pcr_tasa_interes NUMERIC(7, 4) NOT NULL,
  CONSTRAINT ux_tbl_productos_creditos_nombre UNIQUE (pcr_nombre),
  CONSTRAINT chk_tbl_productos_creditos_tasa
    CHECK (pcr_tasa_interes >= 0)
);

CREATE TABLE IF NOT EXISTS tbl_categorias_gastos (
  id_cga BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cga_nombre VARCHAR(120) NOT NULL,
  cga_descripcion VARCHAR(500),
  CONSTRAINT ux_tbl_categorias_gastos_nombre UNIQUE (cga_nombre)
);

CREATE TABLE IF NOT EXISTS tbl_monedas (
  id_mon BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mon_codigo CHAR(3) NOT NULL,
  mon_nombre VARCHAR(80) NOT NULL,
  mon_simbolo VARCHAR(8) NOT NULL,
  mon_decimales BIGINT NOT NULL DEFAULT 2,
  mon_activa BOOLEAN NOT NULL DEFAULT TRUE,
  mon_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_monedas_codigo UNIQUE (mon_codigo),
  CONSTRAINT chk_tbl_monedas_codigo_mayuscula
    CHECK (mon_codigo = upper(mon_codigo)),
  CONSTRAINT chk_tbl_monedas_decimales
    CHECK (mon_decimales BETWEEN 0 AND 6)
);

INSERT INTO tbl_monedas (mon_codigo, mon_nombre, mon_simbolo, mon_decimales) VALUES
  ('COP', 'Peso colombiano', '$', 2),
  ('USD', 'Dolar estadounidense', '$', 2)
ON CONFLICT (mon_codigo) DO NOTHING;

CREATE TABLE IF NOT EXISTS tbl_cajas (
  id_caj BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caj_nombre VARCHAR(120) NOT NULL,
  caj_tipo caja_tipo_enum NOT NULL DEFAULT 'MENOR',
  caj_activa BOOLEAN NOT NULL DEFAULT TRUE,
  caj_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  mon_id BIGINT NOT NULL,
  CONSTRAINT ux_tbl_cajas_org_nombre UNIQUE (org_id, caj_nombre)
);

CREATE TABLE IF NOT EXISTS tbl_gastos (
  id_gas BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gas_fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
  gas_monto NUMERIC(14, 2) NOT NULL,
  caj_id BIGINT NOT NULL REFERENCES tbl_cajas (id_caj) ON DELETE RESTRICT,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  cga_id BIGINT NOT NULL REFERENCES tbl_categorias_gastos (id_cga) ON DELETE RESTRICT,
  CONSTRAINT chk_tbl_gastos_monto CHECK (gas_monto > 0)
);

ALTER TABLE tbl_cajas
  ADD COLUMN IF NOT EXISTS gas_id BIGINT;

DO $$
BEGIN
  ALTER TABLE tbl_cajas
    ADD CONSTRAINT fk_tbl_cajas_gasto
    FOREIGN KEY (gas_id) REFERENCES tbl_gastos (id_gas) ON DELETE SET NULL;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS tbl_sesiones_cajas (
  id_sca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sca_fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT now(),
  sca_fecha_cierre TIMESTAMPTZ,
  sca_monto_inicial NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sca_total_cobrado NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sca_total_gasto NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sca_estado sesion_caja_estado_enum NOT NULL DEFAULT 'ABIERTA',
  caj_id BIGINT NOT NULL REFERENCES tbl_cajas (id_caj) ON DELETE RESTRICT,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  CONSTRAINT chk_tbl_sesiones_cajas_montos
    CHECK (
      sca_monto_inicial >= 0
      AND sca_total_cobrado >= 0
      AND sca_total_gasto >= 0
    ),
  CONSTRAINT chk_tbl_sesiones_cajas_fechas
    CHECK (sca_fecha_cierre IS NULL OR sca_fecha_cierre >= sca_fecha_apertura)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tbl_sesiones_cajas_abierta
  ON tbl_sesiones_cajas (caj_id)
  WHERE sca_estado = 'ABIERTA';

CREATE TABLE IF NOT EXISTS tbl_movimientos_cajas (
  id_mca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mca_tipo movimiento_caja_tipo_enum NOT NULL,
  mca_monto NUMERIC(14, 2) NOT NULL,
  mca_referencia_id BIGINT,
  mca_referencia_tipo movimiento_referencia_tipo_enum,
  mca_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  sca_id BIGINT REFERENCES tbl_sesiones_cajas (id_sca) ON DELETE SET NULL,
  CONSTRAINT chk_tbl_movimientos_cajas_monto CHECK (mca_monto > 0),
  CONSTRAINT chk_tbl_movimientos_cajas_referencia
    CHECK (
      (mca_referencia_id IS NULL AND mca_referencia_tipo IS NULL)
      OR (mca_referencia_id IS NOT NULL AND mca_referencia_tipo IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_tbl_movimientos_cajas_org_fecha
  ON tbl_movimientos_cajas (org_id, mca_creacion DESC);

CREATE TABLE IF NOT EXISTS tbl_creditos (
  id_cre BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cre_total NUMERIC(14, 2) NOT NULL,
  cre_estado credito_estado_enum NOT NULL DEFAULT 'ACTIVO',
  cre_tasa_interes NUMERIC(7, 4) NOT NULL,
  cre_interes_total NUMERIC(14, 2) NOT NULL,
  cre_total_pagar NUMERIC(14, 2) NOT NULL,
  cre_fecha_inicio DATE NOT NULL,
  cre_fecha_fin DATE NOT NULL,
  usu_id BIGINT NOT NULL REFERENCES tbl_usuarios (id_usu) ON DELETE RESTRICT,
  pcr_id BIGINT NOT NULL REFERENCES tbl_productos_creditos (id_pcr) ON DELETE RESTRICT,
  cli_id BIGINT NOT NULL REFERENCES tbl_clientes (id_cli) ON DELETE RESTRICT,
  mon_id BIGINT NOT NULL,
  CONSTRAINT chk_tbl_creditos_valores
    CHECK (
      cre_total > 0
      AND cre_tasa_interes >= 0
      AND cre_interes_total >= 0
      AND cre_total_pagar >= cre_total
    ),
  CONSTRAINT chk_tbl_creditos_fechas
    CHECK (cre_fecha_fin >= cre_fecha_inicio)
);

CREATE INDEX IF NOT EXISTS ix_tbl_creditos_cliente_estado
  ON tbl_creditos (cli_id, cre_estado);

CREATE INDEX IF NOT EXISTS ix_tbl_creditos_usuario_estado
  ON tbl_creditos (usu_id, cre_estado);

CREATE TABLE IF NOT EXISTS tbl_cuotas (
  id_cuo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuo_numero BIGINT NOT NULL,
  cuo_valor NUMERIC(14, 2) NOT NULL,
  cuo_total_pagado NUMERIC(14, 2) NOT NULL DEFAULT 0,
  cuo_estado cuota_estado_enum NOT NULL DEFAULT 'PENDIENTE',
  cuo_fecha_vencimiento DATE NOT NULL,
  cre_id BIGINT NOT NULL REFERENCES tbl_creditos (id_cre) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_cuotas_credito_numero UNIQUE (cre_id, cuo_numero),
  CONSTRAINT chk_tbl_cuotas_valores
    CHECK (
      cuo_numero > 0
      AND cuo_valor > 0
      AND cuo_total_pagado >= 0
      AND cuo_total_pagado <= cuo_valor
    )
);

CREATE INDEX IF NOT EXISTS ix_tbl_cuotas_vencimiento_estado
  ON tbl_cuotas (cuo_fecha_vencimiento, cuo_estado);

CREATE TABLE IF NOT EXISTS tbl_medios_pagos (
  id_med BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  med_nombre VARCHAR(120) NOT NULL,
  med_tipo medio_pago_tipo_enum NOT NULL,
  med_proveedor VARCHAR(120),
  med_referencia_cuenta VARCHAR(120),
  med_titular VARCHAR(180),
  med_activo BOOLEAN NOT NULL DEFAULT TRUE,
  med_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  med_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_medios_pagos_med_tipo UNIQUE (med_tipo),
  CONSTRAINT ux_tbl_medios_pagos_nombre UNIQUE (med_nombre)
);

CREATE TABLE IF NOT EXISTS tbl_pagos (
  id_pag BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pag_monto NUMERIC(14, 2) NOT NULL,
  pag_fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
  pag_referencia VARCHAR(120),
  pag_idempotency_llave UUID NOT NULL DEFAULT gen_random_uuid(),
  pag_estado pago_estado_enum NOT NULL DEFAULT 'REGISTRADO',
  med_id BIGINT NOT NULL REFERENCES tbl_medios_pagos (id_med) ON DELETE RESTRICT,
  mon_id BIGINT NOT NULL,
  CONSTRAINT ux_tbl_pagos_idempotency UNIQUE (pag_idempotency_llave),
  CONSTRAINT chk_tbl_pagos_monto CHECK (pag_monto > 0)
);

-- tbl_pagos ya no referencia directamente a tbl_creditos. El credito se
-- resuelve mediante tbl_cuotas_pagos -> tbl_cuotas -> tbl_creditos.
DROP INDEX IF EXISTS ix_tbl_pagos_credito_fecha;

ALTER TABLE tbl_pagos
  DROP CONSTRAINT IF EXISTS tbl_pagos_cre_id_fkey,
  DROP CONSTRAINT IF EXISTS fk_tbl_pagos_credito,
  DROP COLUMN IF EXISTS cre_id;

-- Compatibilidad para bases donde las tablas ya existian antes de agregar
-- tbl_monedas. Se agrega mon_id, se llena con COP y luego se fuerza NOT NULL.
ALTER TABLE tbl_cajas
  ADD COLUMN IF NOT EXISTS mon_id BIGINT;

ALTER TABLE tbl_creditos
  ADD COLUMN IF NOT EXISTS mon_id BIGINT;

ALTER TABLE tbl_pagos
  ADD COLUMN IF NOT EXISTS mon_id BIGINT;

UPDATE tbl_cajas
SET mon_id = (SELECT id_mon FROM tbl_monedas WHERE mon_codigo = 'COP')
WHERE mon_id IS NULL;

UPDATE tbl_creditos
SET mon_id = (SELECT id_mon FROM tbl_monedas WHERE mon_codigo = 'COP')
WHERE mon_id IS NULL;

UPDATE tbl_pagos
SET mon_id = (SELECT id_mon FROM tbl_monedas WHERE mon_codigo = 'COP')
WHERE mon_id IS NULL;

ALTER TABLE tbl_cajas
  ALTER COLUMN mon_id SET NOT NULL;

ALTER TABLE tbl_creditos
  ALTER COLUMN mon_id SET NOT NULL;

ALTER TABLE tbl_pagos
  ALTER COLUMN mon_id SET NOT NULL;

DO $$
BEGIN
  ALTER TABLE tbl_cajas
    ADD CONSTRAINT fk_tbl_cajas_moneda
    FOREIGN KEY (mon_id) REFERENCES tbl_monedas (id_mon) ON DELETE RESTRICT;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  ALTER TABLE tbl_creditos
    ADD CONSTRAINT fk_tbl_creditos_moneda
    FOREIGN KEY (mon_id) REFERENCES tbl_monedas (id_mon) ON DELETE RESTRICT;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  ALTER TABLE tbl_pagos
    ADD CONSTRAINT fk_tbl_pagos_moneda
    FOREIGN KEY (mon_id) REFERENCES tbl_monedas (id_mon) ON DELETE RESTRICT;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE INDEX IF NOT EXISTS ix_tbl_pagos_fecha
  ON tbl_pagos (pag_fecha DESC);

CREATE TABLE IF NOT EXISTS tbl_cuotas_pagos (
  id_cpa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpa_numero BIGINT,
  cpa_capital NUMERIC(14, 2) NOT NULL DEFAULT 0,
  cpa_interes NUMERIC(14, 2) NOT NULL DEFAULT 0,
  cpa_total NUMERIC(14, 2)
    GENERATED ALWAYS AS (cpa_capital + cpa_interes) STORED,
  cuo_id BIGINT NOT NULL REFERENCES tbl_cuotas (id_cuo) ON DELETE RESTRICT,
  pagos_id BIGINT NOT NULL REFERENCES tbl_pagos (id_pag) ON DELETE CASCADE,
  CONSTRAINT ux_tbl_cuotas_pagos UNIQUE (cuo_id, pagos_id),
  CONSTRAINT chk_tbl_cuotas_pagos_montos
    CHECK (cpa_capital >= 0 AND cpa_interes >= 0 AND cpa_total > 0)
);

CREATE INDEX IF NOT EXISTS ix_tbl_cuotas_pagos_pago
  ON tbl_cuotas_pagos (pagos_id);

CREATE TABLE IF NOT EXISTS tbl_wompi_transacciones (
  id_wtr BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  pag_id BIGINT REFERENCES tbl_pagos (id_pag) ON DELETE SET NULL,
  mon_id BIGINT NOT NULL REFERENCES tbl_monedas (id_mon) ON DELETE RESTRICT,
  wtr_tipo_pago wompi_tipo_pago_enum NOT NULL,
  wtr_estado wompi_estado_enum NOT NULL DEFAULT 'PENDIENTE',
  wtr_monto NUMERIC(14, 2) NOT NULL,
  wtr_monto_centavos BIGINT NOT NULL,
  wtr_referencia VARCHAR(120) NOT NULL,
  wtr_wompi_transaction_id VARCHAR(120),
  wtr_periodo_inicio DATE,
  wtr_periodo_fin DATE,
  wtr_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_tbl_wompi_transacciones_referencia
    UNIQUE (wtr_referencia),
  CONSTRAINT ux_tbl_wompi_transacciones_transaction
    UNIQUE (wtr_wompi_transaction_id),
  CONSTRAINT ux_tbl_wompi_transacciones_pago
    UNIQUE (pag_id),
  CONSTRAINT chk_tbl_wompi_transacciones_monto
    CHECK (wtr_monto > 0 AND wtr_monto_centavos > 0),
  CONSTRAINT chk_tbl_wompi_transacciones_periodo
    CHECK (
      wtr_periodo_inicio IS NULL
      OR wtr_periodo_fin IS NULL
      OR wtr_periodo_fin >= wtr_periodo_inicio
    )
);

CREATE INDEX IF NOT EXISTS ix_tbl_wompi_transacciones_org_creacion
  ON tbl_wompi_transacciones (org_id, wtr_creacion DESC);

CREATE INDEX IF NOT EXISTS ix_tbl_wompi_transacciones_estado
  ON tbl_wompi_transacciones (wtr_estado);

CREATE OR REPLACE VIEW vista_creditos_saldos AS
SELECT
  cr.id_cre,
  cr.cli_id,
  cr.usu_id,
  cr.cre_estado,
  cr.cre_total,
  cr.cre_interes_total,
  cr.cre_total_pagar,
  COALESCE(SUM(cp.cpa_total), 0) AS total_pagado,
  GREATEST(cr.cre_total_pagar - COALESCE(SUM(cp.cpa_total), 0), 0) AS saldo,
  cr.mon_id,
  m.mon_codigo
FROM tbl_creditos cr
JOIN tbl_monedas m
  ON m.id_mon = cr.mon_id
LEFT JOIN tbl_cuotas cu
  ON cu.cre_id = cr.id_cre
LEFT JOIN tbl_cuotas_pagos cp
  ON cp.cuo_id = cu.id_cuo
GROUP BY
  cr.id_cre,
  cr.cli_id,
  cr.usu_id,
  cr.mon_id,
  m.mon_codigo,
  cr.cre_estado,
  cr.cre_total,
  cr.cre_interes_total,
  cr.cre_total_pagar;

DROP VIEW IF EXISTS vista_presupuesto_actual;
DROP VIEW IF EXISTS vista_saldo_caja_menor;

CREATE OR REPLACE VIEW vista_saldo_caja_menor AS
SELECT
  c.id_caj AS caja_menor_id,
  MIN(sc.usu_id) AS responsable_usuario_id,
  c.org_id AS organizacion_id,
  c.mon_id AS moneda_id,
  m.mon_codigo AS moneda_codigo,
  COALESCE(
    SUM(
      CASE
        WHEN mc.mca_tipo IN ('APERTURA', 'RECAUDO', 'AJUSTE_ENTRADA') THEN mc.mca_monto
        WHEN mc.mca_tipo IN ('GASTO', 'DESEMBOLSO_CREDITO', 'AJUSTE_SALIDA') THEN -mc.mca_monto
        ELSE 0
      END
    ),
    0
  ) AS saldo_caja_menor
FROM tbl_cajas c
JOIN tbl_monedas m
  ON m.id_mon = c.mon_id
LEFT JOIN tbl_sesiones_cajas sc
  ON sc.caj_id = c.id_caj
LEFT JOIN tbl_movimientos_cajas mc
  ON mc.sca_id = sc.id_sca
GROUP BY
  c.id_caj,
  c.org_id,
  c.mon_id,
  m.mon_codigo;

CREATE OR REPLACE VIEW vista_presupuesto_actual AS
WITH movimientos_por_caja AS (
  SELECT
    c.id_caj,
    COALESCE(
      SUM(mc.mca_monto) FILTER (
        WHERE mc.mca_tipo IN ('APERTURA', 'RECAUDO', 'AJUSTE_ENTRADA')
      ),
      0
    ) AS recaudado,
    COALESCE(
      SUM(mc.mca_monto) FILTER (WHERE mc.mca_tipo = 'GASTO'),
      0
    ) AS gastos_movimientos,
    COALESCE(
      SUM(mc.mca_monto) FILTER (WHERE mc.mca_tipo = 'DESEMBOLSO_CREDITO'),
      0
    ) AS creditos
  FROM tbl_cajas c
  LEFT JOIN tbl_sesiones_cajas sc
    ON sc.caj_id = c.id_caj
  LEFT JOIN tbl_movimientos_cajas mc
    ON mc.sca_id = sc.id_sca
  GROUP BY c.id_caj
),
gastos_por_caja AS (
  SELECT
    caj_id,
    COALESCE(SUM(gas_monto), 0) AS gastos
  FROM tbl_gastos
  GROUP BY caj_id
)
SELECT
  v.caja_menor_id,
  v.responsable_usuario_id,
  v.organizacion_id,
  v.moneda_id,
  v.moneda_codigo,
  v.saldo_caja_menor AS caja_menor,
  COALESCE(mpc.recaudado, 0) AS recaudado,
  COALESCE(gpc.gastos, 0) + COALESCE(mpc.gastos_movimientos, 0) AS gastos,
  COALESCE(mpc.creditos, 0) AS creditos,
  v.saldo_caja_menor
    + COALESCE(mpc.recaudado, 0)
    - COALESCE(gpc.gastos, 0)
    - COALESCE(mpc.gastos_movimientos, 0)
    - COALESCE(mpc.creditos, 0) AS presupuesto
FROM vista_saldo_caja_menor v
LEFT JOIN movimientos_por_caja mpc
  ON mpc.id_caj = v.caja_menor_id
LEFT JOIN gastos_por_caja gpc
  ON gpc.caj_id = v.caja_menor_id;

DROP TRIGGER IF EXISTS trg_tbl_medios_pagos_actualizacion ON tbl_medios_pagos;
CREATE TRIGGER trg_tbl_medios_pagos_actualizacion
BEFORE UPDATE ON tbl_medios_pagos
FOR EACH ROW EXECUTE FUNCTION actualizar_medios_pagos_fecha();

COMMENT ON TABLE tbl_personas IS
  'Datos base de personas reutilizados por usuarios y clientes.';
COMMENT ON TABLE tbl_usuarios_organizaciones IS
  'Tabla puente entre usuarios, organizaciones y roles.';
COMMENT ON TABLE tbl_rutas_clientes IS
  'Tabla puente que asigna clientes a rutas.';
COMMENT ON TABLE tbl_productos_creditos IS
  'Productos de credito por organizacion, frecuencia e interes.';
COMMENT ON TABLE tbl_cuotas_pagos IS
  'Aplicacion de pagos contra cuotas especificas.';
COMMENT ON TABLE tbl_wompi_transacciones IS
  'Transacciones Wompi asociadas inicialmente a pagos de planes de organizaciones y, a futuro, a pagos de clientes.';
COMMENT ON TABLE tbl_monedas IS
  'Catalogo de monedas usadas por cajas, creditos y pagos.';
COMMENT ON VIEW vista_creditos_saldos IS
  'Saldo de cada credito calculado desde cuotas y aplicaciones de pago.';
COMMENT ON VIEW vista_saldo_caja_menor IS
  'Saldo actual por caja calculado desde movimientos de sesiones de caja.';
COMMENT ON VIEW vista_presupuesto_actual IS
  'Resumen presupuestal por caja: saldo, recaudos, gastos, creditos desembolsados y presupuesto disponible.';

INSERT INTO tbl_roles (rol_tip, rol_nivel) VALUES
  ('ADMINISTRADOR', 1),
  ('COBRADOR', 2),
  ('AUDITOR', 3)
ON CONFLICT (rol_tip) DO NOTHING;

DO $$
DECLARE
  super_admin_existia BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM pg_enum enum_value
    JOIN pg_type enum_type
      ON enum_type.oid = enum_value.enumtypid
    WHERE enum_type.typname = 'rol_tipo_enum'
      AND enum_value.enumlabel = 'SUPER_ADMIN'
  )
  INTO super_admin_existia;

  ALTER TYPE rol_tipo_enum ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

  IF NOT super_admin_existia THEN
    RAISE NOTICE
      'Valor SUPER_ADMIN agregado a rol_tipo_enum. Ejecuta nuevamente este script para sembrar el rol SUPER_ADMIN.';
  ELSE
    UPDATE tbl_roles
    SET rol_nivel = 4
    WHERE rol_tip::text = 'SUPER_ADMIN';

    WITH super_admin_preferido AS (
      INSERT INTO tbl_roles (id_rol, rol_tip, rol_nivel)
      OVERRIDING SYSTEM VALUE
      SELECT 4, 'SUPER_ADMIN'::rol_tipo_enum, 4
      WHERE NOT EXISTS (
        SELECT 1
        FROM tbl_roles
        WHERE rol_tip::text = 'SUPER_ADMIN'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM tbl_roles
        WHERE id_rol = 4
      )
      RETURNING id_rol
    )
    INSERT INTO tbl_roles (rol_tip, rol_nivel)
    SELECT 'SUPER_ADMIN'::rol_tipo_enum, 4
    WHERE NOT EXISTS (SELECT 1 FROM super_admin_preferido)
      AND NOT EXISTS (
        SELECT 1
        FROM tbl_roles
        WHERE rol_tip::text = 'SUPER_ADMIN'
      )
    ON CONFLICT (rol_tip) DO UPDATE
    SET rol_nivel = EXCLUDED.rol_nivel;

    PERFORM setval(
      pg_get_serial_sequence('tbl_roles', 'id_rol'),
      GREATEST((SELECT COALESCE(MAX(id_rol), 1) FROM tbl_roles), 4),
      TRUE
    );
  END IF;

  INSERT INTO tbl_recursos (
    nom,
    rec_orden,
    rec_interface
  )
  SELECT
    recurso.codigo,
    recurso.orden,
    'WEB'::recurso_interface_enum
  FROM (
    VALUES
      ('VER_EMPLEADOS', 10),
      ('CREAR_CAJA_MENOR', 20),
      ('REGISTRAR_FLUJO_CAJA', 30),
      ('CREAR_CREDITOS', 40),
      ('REFINANCIAR_CREDITOS', 50),
      ('MODIFICAR_CREDITOS', 60),
      ('ELIMINAR_CREDITOS', 70),
      ('AGREGAR_CUOTA', 80),
      ('MODIFICAR_MOVIMIENTOS', 90),
      ('ELIMINAR_MOVIMIENTOS', 100)
  ) AS recurso(codigo, orden)
  ON CONFLICT (rec_interface, nom) DO UPDATE
  SET rec_orden = EXCLUDED.rec_orden;

  DELETE FROM tbl_usuarios_organizaciones usuario_org
  USING tbl_roles rol
  WHERE rol.id_rol = usuario_org.rol_id
    AND rol.rol_tip::text IN (
      'VER_EMPLEADOS',
      'CREAR_CAJA_MENOR',
      'REGISTRAR_FLUJO_CAJA',
      'CREAR_CREDITOS',
      'REFINANCIAR_CREDITOS',
      'MODIFICAR_CREDITOS',
      'ELIMINAR_CREDITOS',
      'AGREGAR_CUOTA',
      'MODIFICAR_MOVIMIENTOS',
      'ELIMINAR_MOVIMIENTOS'
    );

  DELETE FROM tbl_roles_recursos rol_recurso
  USING tbl_roles rol
  WHERE rol.id_rol = rol_recurso.rol_id
    AND rol.rol_tip::text IN (
      'VER_EMPLEADOS',
      'CREAR_CAJA_MENOR',
      'REGISTRAR_FLUJO_CAJA',
      'CREAR_CREDITOS',
      'REFINANCIAR_CREDITOS',
      'MODIFICAR_CREDITOS',
      'ELIMINAR_CREDITOS',
      'AGREGAR_CUOTA',
      'MODIFICAR_MOVIMIENTOS',
      'ELIMINAR_MOVIMIENTOS'
    );

  DELETE FROM tbl_roles rol
  WHERE rol.rol_tip::text IN (
    'VER_EMPLEADOS',
    'CREAR_CAJA_MENOR',
    'REGISTRAR_FLUJO_CAJA',
    'CREAR_CREDITOS',
    'REFINANCIAR_CREDITOS',
    'MODIFICAR_CREDITOS',
    'ELIMINAR_CREDITOS',
    'AGREGAR_CUOTA',
    'MODIFICAR_MOVIMIENTOS',
    'ELIMINAR_MOVIMIENTOS'
  );

  INSERT INTO tbl_roles_recursos (rol_id, rec_id)
  SELECT rol.id_rol, recurso.id_rec
  FROM tbl_roles rol
  JOIN tbl_recursos recurso
    ON recurso.rec_interface = 'WEB'
  WHERE rol.rol_tip::text = 'ADMINISTRADOR'
    AND recurso.nom IN (
      'VER_EMPLEADOS',
      'CREAR_CAJA_MENOR',
      'REGISTRAR_FLUJO_CAJA',
      'CREAR_CREDITOS',
      'REFINANCIAR_CREDITOS',
      'MODIFICAR_CREDITOS',
      'ELIMINAR_CREDITOS',
      'AGREGAR_CUOTA',
      'MODIFICAR_MOVIMIENTOS',
      'ELIMINAR_MOVIMIENTOS'
    )
  ON CONFLICT (rec_id, rol_id) DO NOTHING;

  INSERT INTO tbl_roles_recursos (rol_id, rec_id)
  SELECT rol.id_rol, recurso.id_rec
  FROM tbl_roles rol
  JOIN tbl_recursos recurso
    ON recurso.rec_interface = 'WEB'
  WHERE rol.rol_tip::text = 'AUDITOR'
    AND recurso.nom = 'VER_EMPLEADOS'
  ON CONFLICT (rec_id, rol_id) DO NOTHING;

  INSERT INTO tbl_roles_recursos (rol_id, rec_id)
  SELECT rol.id_rol, recurso.id_rec
  FROM tbl_roles rol
  JOIN tbl_recursos recurso
    ON recurso.rec_interface = 'WEB'
  WHERE rol.rol_tip::text = 'COBRADOR'
    AND recurso.nom IN (
      'CREAR_CAJA_MENOR',
      'REGISTRAR_FLUJO_CAJA',
      'CREAR_CREDITOS',
      'REFINANCIAR_CREDITOS',
      'MODIFICAR_CREDITOS',
      'ELIMINAR_CREDITOS',
      'AGREGAR_CUOTA',
      'MODIFICAR_MOVIMIENTOS',
      'ELIMINAR_MOVIMIENTOS'
    )
  ON CONFLICT (rec_id, rol_id) DO NOTHING;
END;
$$;

INSERT INTO tbl_productos_creditos (
  pcr_nombre,
  pcr_frecuencia,
  pcr_tasa_interes
)
SELECT
  producto.nombre,
  producto.frecuencia::producto_credito_frecuencia_enum,
  producto.tasa_interes
FROM (
  VALUES
    ('Credito diario', 'DIARIO', 20.0000),
    ('Credito semanal', 'SEMANAL', 20.0000),
    ('Credito quincenal', 'QUINCENAL', 20.0000),
    ('Credito mensual', 'MENSUAL', 20.0000)
) AS producto(nombre, frecuencia, tasa_interes)
ON CONFLICT (pcr_nombre) DO UPDATE
SET
  pcr_frecuencia = EXCLUDED.pcr_frecuencia,
  pcr_tasa_interes = EXCLUDED.pcr_tasa_interes;

INSERT INTO tbl_medios_pagos (
  med_nombre,
  med_tipo
)
SELECT
  medio.nombre,
  medio.tipo::medio_pago_tipo_enum
FROM (
  VALUES
    ('Efectivo', 'EFECTIVO'),
    ('Transferencia', 'TRANSFERENCIA'),
    ('Tarjeta', 'TARJETA'),
    ('Billetera', 'BILLETERA'),
    ('Otro', 'OTRO')
) AS medio(nombre, tipo)
ON CONFLICT (med_tipo) DO UPDATE
SET
  med_tipo = EXCLUDED.med_tipo,
  med_activo = TRUE;

INSERT INTO tbl_categorias_gastos (cga_nombre, cga_descripcion) VALUES
  ('TRANSPORTE', 'Gastos de transporte'),
  ('PAPELERIA', 'Papeleria e insumos'),
  ('COMISION', 'Comisiones operativas'),
  ('OTRO', 'Otros gastos')
ON CONFLICT (cga_nombre) DO NOTHING;

-- ==============================================================================
-- TBL_NOTIFICACIONES
-- ==============================================================================

DO $$
BEGIN
  CREATE TYPE notificacion_tipo_enum AS ENUM (
    'CREDITO_APROBADO',
    'PAGO_RECIBIDO',
    'CREDITO_FINALIZADO'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$
BEGIN
  CREATE TYPE notificacion_canal_enum AS ENUM (
    'CORREO',
    'WHATSAPP'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$
BEGIN
  CREATE TYPE notificacion_estado_enum AS ENUM (
    'PENDIENTE',
    'ENVIADA',
    'FALLIDA'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS tbl_notificaciones (
  id_not BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL,
  cli_id BIGINT NOT NULL,
  cre_id BIGINT,
  pag_id BIGINT,
  not_tipo notificacion_tipo_enum NOT NULL,
  not_canal notificacion_canal_enum NOT NULL,
  not_estado notificacion_estado_enum NOT NULL DEFAULT 'PENDIENTE',
  not_destinatario VARCHAR(180) NOT NULL,
  not_referencia_externa VARCHAR(255),
  not_error TEXT,
  not_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  not_envio TIMESTAMPTZ,
  
  CONSTRAINT fk_tbl_notificaciones_org FOREIGN KEY (org_id)
    REFERENCES tbl_organizaciones (id_org) ON DELETE CASCADE,
  CONSTRAINT fk_tbl_notificaciones_cli FOREIGN KEY (cli_id)
    REFERENCES tbl_clientes (id_cli) ON DELETE CASCADE,
  CONSTRAINT fk_tbl_notificaciones_cre FOREIGN KEY (cre_id)
    REFERENCES tbl_creditos (id_cre) ON DELETE CASCADE,
  CONSTRAINT fk_tbl_notificaciones_pag FOREIGN KEY (pag_id)
    REFERENCES tbl_pagos (id_pag) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_notificaciones_org ON tbl_notificaciones (org_id);
CREATE INDEX IF NOT EXISTS idx_tbl_notificaciones_cli ON tbl_notificaciones (cli_id);
CREATE INDEX IF NOT EXISTS idx_tbl_notificaciones_cre ON tbl_notificaciones (cre_id);
CREATE INDEX IF NOT EXISTS idx_tbl_notificaciones_estado ON tbl_notificaciones (not_estado);

COMMIT;
