CREATE TABLE IF NOT EXISTS recurso (
  recurso_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rol_recurso (
  rol_id SMALLINT NOT NULL REFERENCES rol (rol_id) ON DELETE CASCADE,
  recurso_id SMALLINT NOT NULL REFERENCES recurso (recurso_id) ON DELETE CASCADE,
  asignado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (rol_id, recurso_id)
);

INSERT INTO recurso (codigo, nombre) VALUES
  ('CREAR_CAJA_MENOR', 'Crear caja menor'),
  ('REGISTRAR_FLUJO_CAJA', 'Registrar flujo en caja menor'),
  ('CREAR_CREDITOS', 'Crear creditos'),
  ('REFINANCIAR_CREDITOS', 'Refinanciar creditos'),
  ('AGREGAR_CUOTA', 'Agregar cuota')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    actualizado_en = now();

INSERT INTO rol (codigo, nombre) VALUES
  ('CREAR_CAJA_MENOR', 'Permiso crear caja menor'),
  ('REGISTRAR_FLUJO_CAJA', 'Permiso registrar flujo en caja menor'),
  ('CREAR_CREDITOS', 'Permiso crear creditos'),
  ('REFINANCIAR_CREDITOS', 'Permiso refinanciar creditos'),
  ('AGREGAR_CUOTA', 'Permiso agregar cuota')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre;

INSERT INTO rol_recurso (rol_id, recurso_id)
SELECT r.rol_id, rec.recurso_id
FROM rol r
JOIN recurso rec ON rec.codigo = r.codigo
WHERE r.codigo IN (
  'CREAR_CAJA_MENOR',
  'REGISTRAR_FLUJO_CAJA',
  'CREAR_CREDITOS',
  'REFINANCIAR_CREDITOS',
  'AGREGAR_CUOTA'
)
ON CONFLICT DO NOTHING;

INSERT INTO rol_recurso (rol_id, recurso_id)
SELECT admin.rol_id, rec.recurso_id
FROM rol admin
JOIN recurso rec ON rec.codigo IN (
  'CREAR_CAJA_MENOR',
  'REGISTRAR_FLUJO_CAJA',
  'CREAR_CREDITOS',
  'REFINANCIAR_CREDITOS',
  'AGREGAR_CUOTA'
)
WHERE admin.codigo = 'ADMINISTRADOR'
ON CONFLICT DO NOTHING;

INSERT INTO usuario_rol (usuario_id, rol_id)
SELECT cobrador.usuario_id, permiso.rol_id
FROM usuario_rol cobrador
JOIN rol rol_base
  ON rol_base.rol_id = cobrador.rol_id
 AND rol_base.codigo = 'COBRADOR'
JOIN rol permiso
  ON permiso.codigo IN (
    'CREAR_CAJA_MENOR',
    'REGISTRAR_FLUJO_CAJA',
    'CREAR_CREDITOS',
    'REFINANCIAR_CREDITOS',
    'AGREGAR_CUOTA'
  )
ON CONFLICT DO NOTHING;
